[theme]
primaryColor = "#0D47A1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
